# Evaluation sub-pipeline to choose - 
# parse (parse responses) : This step logs requests that couldn't be parsed so that their format can be fixed
# format_fix (fix format using an LLM)
# heuristic_requests (form and send batched requests)
# batch_monitor (monitor the state of requests, download raw results on completion)
# heuristic_eval (save LLM heuristic eval responses)
# deterministic_eval
# analysis
# Common config
# eval_step: "parse"
eval_step: "analysis"

evaluation_folder_path: "${data_folderpath}/evaluation"

filenames:
  - qwen4bbase
  - qwen4bft
  - llama8bbase
  - llama8bft
  # - residual
  # - chatgpt5mini


# Fix format additional config
format_fix_indices:
  - []

# Monitor batches additional config
# batch_info:
#   - [qwen4bbase, gemini25flash, "batches/ua06pmyru09mp73rnswb31gqorzfgbw24xw2", google]
#   - [llama8bft, gpt5mini, "batch_69f1f5a7cc708190a9efd3e6ab85909d", openai]

# Heuristic evaluation additional config
evaluator_models:
  - provider: openai
    model: gpt-5-mini
    name: gpt5mini
    config:
      reasoning:
        effort: low
  - provider: google
    model: gemini-2.5-flash
    name: gemini25flash
    config:
      thinking_config:
        include_thoughts: false
        thinking_budget: 0

create_requests: true
send_requests: false

# Heuristic evals, deterministic evals common filepath
evaluations_granular_filename: "recipefusion_evaluations"

# Analysis config
analysis:
 filter_out_values: [rationale, RecipeA_json_errors, RecipeB_json_errors, RecipeFusion_json_errors, RecipeA_dag_errors, RecipeB_dag_errors, RecipeFusion_dag_errors]
 drop_columns: [inference_key]

# Common config
suffixes:
  inference_responses: "_inference_responses"
  parse: "_parsed"
  format_fixed: "_format_fixed"
  heuristic_requests: null # Unused