defaults:
  - model: llama_3_8b
  - hardware: a10_gpu
  - data: fusion_v1
  - /paths: default_paths
  - /prompts: fusion_chef
  - training: train_default
  - inference:  inference_default
  - merging: merge_default
  - _self_
  # - optional merging: merge_default

# Shared global settings
seed: 43
debug: false